version: '2.0'
services:
  spark-master:
    ports: ["5500:8080"]
    image: "spark-base"
    container_name: spark-master
    working_dir: /usr/local/spark-2.1.1-bin-hadoop2.7/bin
    command: ["spark-class", "org.apache.spark.deploy.master.Master"]
    volumes: ["/wrk/docker:/wrk/docker/"]
  
  spark-worker-1: 
    image: "spark-base"
    working_dir: /usr/local/spark-2.1.1-bin-hadoop2.7/bin
    command: ["spark-class","org.apache.spark.deploy.worker.Worker","spark://spark-master:7077","-c","2","-m","4G"]
    volumes: ["/wrk/docker:/wrk/docker/"]
  
  spark-worker-2: 
    image: "spark-base"
    working_dir: /usr/local/spark-2.1.1-bin-hadoop2.7/bin
    command: ["spark-class","org.apache.spark.deploy.worker.Worker","spark://spark-master:7077","-c","2","-m","4G"]
    volumes: ["/wrk/docker:/wrk/docker/"]
    

      